export const GET_CURRENT_DISTANCE = 'distance/GET_CURRENT_DISTANCE';
export const GET_CURRENT_DIRECTION = 'distance/GET_CURRENT_DIRECTION';
export const CHECK_POSITION_IN_VANCOUVER = 'distance/CHECK_POSITION_IN_VANCOUVER';
export const RESET_DIRECTION = 'distance/RESET_DIRECTION';
